services:
    Ethinking\PushConnectorBundle\Controller\Controller:
        parent: EzSystems\EzPlatformAdminUiBundle\Controller\Controller

    Ethinking\PushConnectorBundle\Controller\:
        autowire: true
        public: true
        resource: '../../Controller/*'
        exclude: '../../Controller/{Controller.php}'
