services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    EzPlatform\PushConnectorBundle\Entity\MainSettings: ~

    EzPlatform\PushConnector\EzPlatform\Repository\Form\Factory\FormFactory: ~