services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzPlatform\PushConnector\EzPlatform\UI\Menu\EventSubscriber\:
        resource: '../../../../../lib/EzPlatform/UI/Menu/EventSubscriber/*'