= EzPlatform Push Connector
ethinking <push.delivery@ethinking.de>

The Push Delivery Connector from ethinking GmbH lets you enhance your
CMS experience with providing access to new ways of reaching your
customers using your created content. It establishes the possibility to
send push notifi cations to various platforms from the inside of your
CMS. The connector will provide its own tabs next to the admin section
to let your CMS admin easily set up all necessary connections. Moreover,
it is designed to create and alter distribution channels or push
templates.

=== Installation

The recommended way to install a library is via composer:

[source,php]
----
composer require ethinking/push-api dev-master
composer require ethinking/ezplatform-push-connector dev-master
----

=== Preparation

1) Create ezplatform_push_connector.yaml in the config/routes/ with the
next code:

[source,yaml]
----
ezplatform_push_connector:
  resource: "@EzPlatformPushConnectorBundle/Resources/config/routing.yaml"
  prefix:   /
----
2) Add a yaml file in config/packages with the format:

[source,yaml]
----
ezplatform:
    system:
        admin_group:
            push_config:
                content_types_map:
                    article:
                        webpush:
                          fields:
                            title: '<content_field_title>'
                            message: '<content_field_message>'
                          enabled: true
----
Replace <content_field_title> and <content_field_message> with the identifier of respective content fields.This maps the fields in content to be pushed with the push payload .Import this yaml file in config/packages/ezplatform.yaml

Example:
File config/packages/push_mapping.yaml with content:
[source,yaml]
----
ezplatform:
    system:
        admin_group:
            push_config:
                content_types_map:
                    article:
                        webpush:
                          fields:
                            title: 'push_title'
                            message: 'push_summary'
                          enabled: true
----
And import this file in config/packages/ezplatform.yaml:

[source,yaml]
----
imports:
    - push_mapping.yaml
----

3) Update assets

[source,php]
----
yarn encore dev
----

4) Clear cache

[source,php]
----
php bin/console c:c
----

=== Errors

if you're getting an error about missing dependencies in the
entrypoints.json, try to delete manually "public/assets/ezplatform"
directory and update assets again using command "composer install".

Also make sure you have the next records in the config/bundles.php:

----
Ethinking\PushConnectorBundle\EzPlatformPushConnectorBundle::class => ['all' => true],
Ethinking\EthinkingPushApiBundle\EthinkingPushApiBundle::class => ['all' => true],
----

=== Configuration

After installation, a new menu item "Push" will appear in the navigation with the sub menu item "Main settings"
http://YOUR_WEBSITE_URL/admin/push/mainsettings

Fill out fields on the "Main settings" page with the received information.

Create a new channel on the "Channels" page http://YOUR_WEBSITE_URL/admin/push/channel

=== Usage
Add embed code placeholder into your twig template
----
{{ ez_push_connector_embed_code() }}
----

=== Dependencies

[source,json]
----
{
    "symfony/dependency-injection": "^5.0",
    "symfony/http-kernel": "^5.0",
    "symfony/http-foundation": "^4.4|^5.0",
    "symfony/http-client": "^4.3|^5.0",
    "symfony/http-client-contracts": "^1.1.8|^2",
    "symfony/validator": "^3.4.30|^4.3.3|^5.0",
    "symfony/mime": "^4.3|^5.0",
    "ethinking/push-api": "dev-master"
}
----
