services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ethinking\PushConnectorBundle\Templating\Twig\Extension\EmbedCodeExtension:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Ethinking\EthinkingPushApiBundle\Service\PushApiService'
            - '@Symfony\Component\HttpFoundation\UrlHelper'