services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ethinking\PushConnectorBundle\Templating\Twig\Extension\EmbedCodeExtension:
        arguments:
            - '@Ethinking\PushConnectorBundle\Service\PushService'
            - '@Symfony\Component\HttpFoundation\UrlHelper'