services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    #Global to check permission in e.g Controller
    EzPlatform\PushConnector\EzPlatform\UI\Permission\PermissionChecker: ~

    EzPlatform\PushConnectorBundle\Repository\MainSettingsRepository:
        arguments:
            - '@doctrine'

    Ethinking\EthinkingPushApiBundle\Service\PushApiService:
        arguments:
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'
            - '@logger'

    EzPlatform\PushConnectorBundle\Service\PushService:
        arguments:
            - '@Ethinking\EthinkingPushApiBundle\Service\PushApiService'
            - '@EzPlatform\PushConnectorBundle\Repository\MainSettingsRepository'
