services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    #Global to check permission in e.g Controller
    Ethinking\PushConnector\EzPlatform\UI\Permission\PermissionChecker: ~

    Ethinking\EthinkingPushApiBundle\Service\PushApiService:
        arguments:
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'
            - '@logger'
            - '@Symfony\Contracts\Cache\CacheInterface'

    Ethinking\PushConnectorBundle\Service\PushService:
        arguments:
            - '@Ethinking\EthinkingPushApiBundle\Service\PushApiService'
            - '@Doctrine\ORM\EntityManagerInterface'
