services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    #Connector channel configuration
    Ethinking\PushConnector\Connector\Channels\Provider\:
        resource: '../../../../../lib/Connector/Channels/Provider/*'
        lazy: Ethinking\PushConnector\Connector\Channels\Provider\PushConnectorChannelsInterface
        tags: ['ezplatform.push_connector.channels']

    Ethinking\PushConnector\Connector\Channels\Registry\ChannelsRegistry: ~

    Ethinking\PushConnector\Connector\Services\ConfigurationDefinitionService: ~


    Ethinking\PushConnector\Connector\Channels\Mapper\:
        resource: '../../../../../lib/Connector/Channels/Mapper/*'
        lazy: Ethinking\PushConnector\Connector\Channels\Provider\ChannelConfiguration.php
