services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    #Connector channel configuration
    EzPlatform\PushConnector\Connector\Channels\Mapper\Content\Fields\:
        resource: '../../../../../lib/Connector/Channels/Mapper/Content/Fields/*'
        tags: ['ezplatform.push_connector.content_fields_mapper']

    EzPlatform\PushConnector\Connector\Channels\Registry\ContentFieldsMapperRegistry:
        arguments:
            - !tagged_iterator ezplatform.push_connector.content_fields_mapper

    #FieldType helpers
    EzPlatform\PushConnector\Connector\Channels\Mapper\Content\Fields\Helper\ImageAssetMapper: ~

    EzPlatform\PushConnector\Connector\Channels\Registry\ContentFieldsMapperRegistryInterface: '@EzPlatform\PushConnector\Connector\Channels\Registry\ContentFieldsMapperRegistry'

    #Content field mapping
    EzPlatform\PushConnector\Connector\Services\ContentMapperService: ~

    #PushService
    EzPlatform\PushConnector\Connector\Services\ContentPushService: ~

