services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzPlatform\PushConnector\Connector\Channels\EventSubscriber\:
        resource: '../../../../../lib/Connector/Channels/EventSubscriber/*'